(function () {
    var SCHOOL_CATEGORY_RAW_CODES = {
      "Academia Ciudad Cristiana Cayey": ["SRM"],
      "Academia Cristo Milagros": ["JRF", "SRF"],
      "Academia Interamericana": ["JM", "JRM", "SRM"],
      "ACC Toa Baja": ["JM", "JRM", "MM", "SRM"],
      "ADC Hato Tejas": ["JM"],
      "ADC Vega Alta": ["JM", "JRM", "MM"],
      "Adela Rolón, Toa Alta": ["PM"],
      "Adjuntas High": ["PF"],
      "Alespi, Orocovis": ["JRM", "SRM"],
      "American School": ["JM", "JRM", "MM", "SRF", "SRM"],
      "Ana Roque, Humacao": ["PM"],
      "AOBA Salinas": ["JRM"],
      "API Ponce": ["MM"],
      "ASAES Sabana Grande": ["JM", "SRM"],
      "Aurea Quiles": ["PM"],
      "Ave María de Ponce": ["SRM"],
      "B-You": ["SRM"],
      "Baldwin": ["JM"],
      "Bautista Caguas": ["SRM"],
      "Bautista Carolina": ["SRF", "SRM"],
      "Bayamón Military Academy": ["JM", "JRF", "JRM", "MM", "SRF", "SRM"],
      "Belén Blanco": ["PF"],
      "Caguas Private School": ["JM", "JRM", "MM", "SRF", "SRM"],
      "Calasanz": ["JM"],
      "Capitán Correa, Hatillo": ["SRF", "SRM"],
      "Carib Aguadilla": ["JM", "JRM", "SRM"],
      "Caribbean Ponce": ["SRM"],
      "Catalina Morales": ["JRM", "PM"],
      "CBA Fajardo": ["JRM"],
      "Christian Military Academy": ["SRM"],
      "CIEM, Carolina": ["JRM", "SRM"],
      "Cohelet, Las Piedras": ["JM", "JRM", "MM", "SRM"],
      "Colegio Adianez": ["JM", "JRF", "JRM", "MM", "SRF", "SRM"],
      "Conchita Cuevas": ["PF", "PM", "SRM"],
      "CRCA Camuy": ["SRM"],
      "Cristo Redentor, San Lorenzo": ["JRM", "MM", "SRM"],
      "Cristo Rey, Ponce": ["JRM", "SRM"],
      "Cupeyville School": ["SRM"],
      "De Diego, Carolina": ["JRM", "SRM"],
      "Del Carmen Hatillo": ["JM", "JRF", "SRF", "SRM"],
      "Dr. Carlos González, Aguada": ["PF", "PM"],
      "Dr. Pila, Ponce": ["PM"],
      "ECEDAO, Salinas": ["JRF", "SRF"],
      "Edison Caguas": ["JRM"],
      "Eloisa Pascual, Caguas": ["PM"],
      "Emadrian Bayamón": ["JM", "JRM", "MM", "SRF", "SRM"],
      "Emilio E. Delgado de Corozal": ["PM"],
      "ESCAED": ["JRM", "MM"],
      "Escuela del Deporte de SJ": ["JM", "JRM", "MM", "SRM"],
      "ESOTY Yauco": ["PF", "PM"],
      "Eva Patria Custodio": ["PM"],
      "Family Christian": ["JM", "JRF", "JRM", "MM", "SRM"],
      "Fernando Callejo, Barceloneta": ["PM"],
      "Fernando Suria Barceloneta": ["PM"],
      "Fountain Carolina": ["JM", "MM", "SRM"],
      "Fountain, Guayama": ["JRM", "SRM"],
      "Francisco Manrique": ["JRM", "MM", "PM", "SRM", "PF"],
      "Francisco Mendoza, Isabela": ["PM"],
      "Gabriela Mistral San Juan": ["PM"],
      "Gautier Benitez Caguas": ["PM"],
      "Guamani, Guayama": ["JRM", "MM", "SRM"],
      "HEA Manatí": ["JRM"],
      "Heriberto Domenech, Isabela": ["PM"],
      "Hostos, Mayagüez": ["PM"],
      "IMEI": ["SRM"],
      "Inmaculada Santurce": ["JM"],
      "Instituto Desarrollo del Niño": ["JM", "JRM", "SRF", "SRM", "MM"],
      "Inter San Germán": ["SRM"],
      "Isabel Flores, Juncos": ["PM"],
      "Jireh Kingdom Río Grande": ["JM", "JRM", "MM", "SRF", "SRM"],
      "Jose Collazo, Juncos": ["PM", "SRM"],
      "Jose M. Lazaro Carolina": ["PM"],
      "José Rojas de Orocovis": ["PM"],
      "Josefina Leon Zayas, Jayuya": ["PF", "SRF"],
      "Juan Lino": ["MM"],
      "Juan Ponce León, Florida": ["PM"],
      "Juana Rosario de Aguada": ["JM"],
      "Kingdom Dorado": ["JM", "JRM", "MM", "SRF", "SRM"],
      "La Milagrosa Cayey": ["JRM", "MM", "SRM"],
      "La Milagrosa Ponce": ["JRM"],
      "La Salle Bayamón": ["JM", "JRM", "MM", "SRM"],
      "La Vieja de Naranjito": ["PM"],
      "La Vieja Utuado": ["PM"],
      "Lares High": ["PF", "PM", "SRF"],
      "Leadership Christian Academy": ["JRF", "JRM", "SRF", "SRM"],
      "Leonides de Lajas": ["PM"],
      "Liceo Aguadillano": ["SRM"],
      "Lino Padron": ["PM"],
      "LMM - Añasco": ["PM"],
      "LMM Barranquitas": ["JRM", "PF", "PM", "SRF", "SRM"],
      "Lorenzo Vizcarrondo, Carolina": ["PM", "SRM"],
      "Lu-Anna San Sebastián": ["SRM"],
      "Luis Felipe Crespo, Camuy": ["PM"],
      "Luis Llorens Torres JD": ["PF"],
      "Luis Muñoz Rivera Quebradillas": ["JM"],
      "Luz A. Calderon": ["PM"],
      "Lysander Borrero": ["PM"],
      "Madelcar Academy": ["JRM"],
      "Manuel A. Toro Caguas": ["PM"],
      "Manuel Ramos, Quebradillas": ["PM"],
      "Mar Azul": ["SRM"],
      "María T. Piñeiro Toa Baja": ["PM"],
      "Marista Guaynabo": ["JM", "SRM"],
      "Marista Manati": ["JM", "MM"],
      "Masis School": ["JRM", "SRM"],
      "Mayagüez Academy": ["JRF", "SRF", "SRM"],
      "Medardo Carazo Trujillo Alto": ["PM"],
      "Mi Cuido, Las Piedras": ["JRM", "SRM"],
      "Millán, Carolina": ["PM"],
      "Mirmar Arecibo": ["JM", "MM"],
      "MML de San Sebastián": ["PM"],
      "MMM Bayamon": ["PM"],
      "MMM de Cayey": ["PM"],
      "New Generation": ["SRF"],
      "Notre Dame": ["JM", "JRF", "JRM", "MM", "SRF", "SRM"],
      "NOVA Salinas": ["JM", "MM", "SRM"],
      "NW Bilingual, Vega Alta": ["JM", "JRF", "JRM", "SRF", "SRM"],
      "Padre Anibal": ["PF"],
      "Palermo Isla Verde": ["JRF", "JRM", "MM", "SRF", "SRM"],
      "Paradiso Arecibo": ["JM", "JRM"],
      "Patria Latorre, San Sebastián": ["PM"],
      "Pedro Falú, Río Grande": ["PM", "SRM"],
      "Perpetuo de Salinas": ["JM"],
      "Perpetuo Socorro, Humacao": ["SRM"],
      "Petra Corretjer de Manatí": ["PM"],
      "Ponce High": ["PM"],
      "PRBSA Morovis": ["JM", "JRM", "MM", "SRM"],
      "Presby Carolina": ["JM", "JRM", "MM", "SRF", "SRM"],
      "Pruebalo": ["JM", "JRM"],
      "Rajohnyari": ["JM", "JRM", "MM"],
      "Ramón Davila, Coamo": ["PM"],
      "Ramon Power, Las Piedras": ["PF", "PM", "SRF"],
      "Remington": ["JRM"],
      "Republica del Peru (Hall)": ["PM"],
      "Robertson School": ["JRM", "MM", "SRF"],
      "Roque Díaz Tizol": ["JRM", "SRM"],
      "Sagrada Familia, Corozal": ["JM", "JRM"],
      "Sagrado Corazón, de Ponce": ["JM", "SRM"],
      "Saint Francis School": ["JM", "JRF", "JRM", "MM", "SRF", "SRM"],
      "Saint Mónica, Santurce": ["JRM", "MM", "SRF", "SRM"],
      "San Antonio Guayama": ["MM", "SRM", "JM"],
      "San Benito Mayagüez": ["JM", "JRM", "MM", "SRM"],
      "San Conrado, Ponce": ["JRF", "JRM", "SRF"],
      "San Felipe, Arecibo": ["JM", "JRF", "JRM", "SRF", "SRM"],
      "San Ignacio de Loyola": ["JM", "JRM", "SRM"],
      "San José, Río Piedras": ["JM", "JRM", "MM", "SRM"],
      "San Juan Bosco": ["JM", "JRM", "SRM"],
      "San Rafael, Quebradillas": ["JM", "JRF", "JRM", "MM", "SRF", "SRM"],
      "Santa Gema, Carolina": ["SRM"],
      "Segundo Ruiz Belvis": ["PM"],
      "Step by Step de Gurabo": ["JM", "JRM", "MM"],
      "SUM Maricao": ["PM"],
      "Trina Padilla, Arecibo": ["PM", "SRM"],
      "UHS Río Piedras": ["JM", "SRF", "SRM"],
      "Urbana Aguas Buenas": ["PF", "PM", "SRF"],
      "Valvanera de Coamo": ["JRM", "MM", "SRM"],
      "Veve Calzada, Fajardo": ["PM", "SRM"],
      "Victory, Ponce": ["JM", "JRM", "MM", "SRM"],
      "Vigotsky Barceloneta": ["JRM", "MM", "SRM"],
      "Vocacional Arecibo": ["PF", "PM"],
      "Vocacional Caguas": ["PM"],
      "Vocacional Canovanas": ["PF", "PM"],
      "Vocacional Cayey": ["JRM", "PM"],
      "Vocacional Loiza": ["PM"],
      "Vocacional Naranjito": ["PM"],
      "Vocacional Ponce": ["PF", "PM", "SRM"],
      "Walks Webs": ["SRM"],
      "YAA Cabo Rojo": ["JM", "JRF", "JRM", "MM", "SRF"],
      "Yarah, Toa Alta": ["SRF", "SRM"]
    };

    var CATEGORY_CODE_METADATA = {
        "JM": { category: "Juvenil", gender: "Masculino" },
        "JF": { category: "Juvenil", gender: "Femenino" },
        "JRM": { category: "Junior", gender: "Masculino" },
        "JRF": { category: "Junior", gender: "Femenino" },
        "MM": { category: "Mini", gender: "Masculino" },
        "MF": { category: "Mini", gender: "Femenino" },
        "PM": { category: "Publica", gender: "Masculino" },
        "PF": { category: "Publica", gender: "Femenino" },
        "SRM": { category: "Senior", gender: "Masculino" },
        "SRF": { category: "Senior", gender: "Femenino" }
    };

    function normalizeSchoolKey(value) {
        return String(value || '')
            .normalize('NFD')
            .replace(/[\u0300-\u036f]/g, '')
            .toLowerCase()
            .replace(/&/g, ' and ')
            .replace(/[^a-z0-9]+/g, ' ')
            .trim();
    }

    function buildEligibilityRulesByCategory_() {
        var out = {};
        Object.keys(SCHOOL_CATEGORY_RAW_CODES).forEach(function (school) {
            var key = normalizeSchoolKey(school);
            var uniqueCodes = [];
            (SCHOOL_CATEGORY_RAW_CODES[school] || []).forEach(function (code) {
                var clean = String(code || '').trim().toUpperCase();
                if (!CATEGORY_CODE_METADATA[clean]) return;
                if (uniqueCodes.indexOf(clean) === -1) uniqueCodes.push(clean);
            });
            uniqueCodes.sort();
            out[key] = {
                school: school,
                expected_codes: uniqueCodes
            };
        });
        return out;
    }

    window.SCHOOL_CATEGORY_RAW_CODES = SCHOOL_CATEGORY_RAW_CODES;
    window.CATEGORY_CODE_METADATA = CATEGORY_CODE_METADATA;
    window.buildEligibilityRulesByCategory_ = buildEligibilityRulesByCategory_;
    window.ELIGIBILITY_RULES_BY_CATEGORY = buildEligibilityRulesByCategory_();
})();
